version: '3.6'
services:

  influxdb:
    image: influxdb:1.5-alpine
    restart: always
    ports:
      - 8086:8086

  chronograf:
    image: chronograf:1.7-alpine
    restart: always
    ports:
      - 8888:8888

  postgres:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_PASSWORD: iamaninsecurepassword
      POSTGRES_USER: beehive_user
      POSTGRES_DB: beehive
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/postgresql

  beehive-service:
    build:
      context: ./build
      dockerfile: local/Dockerfile
    depends_on:
      - postgres
    environment:
      ENV: local
      INFLUX_DB_HOST: influxdb
      PGPASSWORD: iamaninsecurepassword
      PGUSER: beehive_user
      PGDATABASE: beehive
      PGHOST: postgres
      BEEHIVE_ENABLE_EVENTS: "no"
      AWS_REGION: us-east-1
    ports:
      - 4022:4000
    command: "scripts/setup-and-startup.sh"
    volumes:
      - type: bind
        source: ./
        target: /app
